#module MPIPencilWrapper

# 
# Improved PencilFFT MPI utilities     (compatible with 2-D domain-decomposed
# grids generated by PencilArrays / PencilFFTs)
# 
# Highlights
#   - Gracefully auto-initialises MPI and validates communicators.
#   - Unified wrapper `PencilPlanRFFT` works for real<->complex and complex<->complex
#     transforms on x-y pencil layouts.
#   ¢ Helper allocators create arrays that inherit the *exact* pencil layout of
#     the plan, so work buffers live on the right MPI ranks.
#   ¢ Generic `localview`, `localindices_dim`, etc., abstract over serial and
#     parallel cases, letting upper-level code stay agnostic.
# 

# using MPI
# using PencilFFTs, PencilArrays

# Ensure MPI is up (safe if already).
MPI.Initialized() || MPI.Init()

# 
# Type definition
# 

struct PencilPlanRFFT{F,B,Meta}
    forward :: F
    backward:: B
    meta    :: Meta   # NamedTuple of metadata
end

# 
# MPI helper  returns a valid communicator (throws otherwise)
# 

function _ensure_comm(comm::MPI.Comm = MPI.COMM_WORLD)
    MPI.Initialized() || MPI.Init()
    # MPI.Comm_valid was removed in MPI.jl v0.20+
    # Basic validation: check if we can get rank and size
    try
        MPI.Comm_rank(comm)
        MPI.Comm_size(comm)
    catch
        throw(ArgumentError("Invalid MPI communicator"))
    end
    return comm
end

"""Public wrapper to validate and return an MPI communicator."""
ensure_comm(comm::MPI.Comm = MPI.COMM_WORLD) = _ensure_comm(comm)

# 
# Trait helpers
# 

isparallel(plan::PencilPlanRFFT) = plan.meta.parallel
Base.isreal(plan::PencilPlanRFFT) = plan.meta.real_transform
import PencilFFTs: get_comm
get_comm(plan::PencilPlanRFFT) = plan.meta.comm
eltype_physical( plan::PencilPlanRFFT) = plan.meta.T_phys
eltype_spectral( plan::PencilPlanRFFT) = plan.meta.T_spec
physical_sizes(  plan::PencilPlanRFFT) = plan.meta.phys_dims
spectral_sizes(  plan::PencilPlanRFFT) = plan.meta.spec_dims

# 
# Real FFT output sizing helper
# 

rfft_output_size(dims::NTuple{N,Int}) where {N} = ntuple(i -> i == N ? div(dims[i], 2) + 1 : dims[i], N)

# 
# Plan construction (autodetects real vs complex path)
# 

function make_pencil_plan_rfft(::Type{T}, dims::NTuple{N,Int};
                               comm::MPI.Comm = MPI.COMM_WORLD,
                               real_transform::Bool = true) where {T,N}
    comm = _ensure_comm(comm)

    N>0 || throw(ArgumentError("Dimension tuple cannot be empty"))
    all(>(0), dims) || throw(ArgumentError("Dimensions must be positive: $dims"))

    # Decide element types and plan builders
    if real_transform
        !(T <: Real) && throw(ArgumentError("Real transform requires real eltype, got $T"))
        T_phys = T
        T_spec = Complex{T}
        phys_dims = dims
        spec_dims = rfft_output_size(dims)
        fplan = PencilFFTs.plan_rfft(T_phys, phys_dims; comm)
        bplan = PencilFFTs.plan_irfft(T_spec, spec_dims, phys_dims[end]; comm)
    else
        T_phys = T_spec = T <: Complex ? T : Complex{T}
        phys_dims = spec_dims = dims
        fplan = PencilFFTs.plan_fft(T_phys, phys_dims; comm)
        bplan = PencilFFTs.plan_ifft(T_spec, spec_dims; comm)
    end

    meta = (; dims,
             phys_dims,
             spec_dims,
             T_phys,
             T_spec,
             parallel = true,
             real_transform,
             comm,
             created_at = time())
    return PencilPlanRFFT(fplan, bplan, meta)
end

# 
# Local-view helpers (serial fallback)
# 

# Use existing localview helpers if already defined (e.g., from timestep module)
# Avoid redefining to prevent method overwriting during precompilation.

function _alloc_array(::Type{T}, dims, comm) where T
    try
        return PencilArrays.PencilArray{T}(undef, dims; comm)
    catch
        # serial fallback for testing/one-rank runs
        return Array{T}(undef, dims)
    end
end

if !isdefined(@__MODULE__, :alloc_phys)
    alloc_phys(::Type{T}, plan::PencilPlanRFFT) where T = _alloc_array(T, plan.meta.phys_dims, plan.meta.comm)
end
if !isdefined(@__MODULE__, :alloc_spec)
    alloc_spec(::Type{T}, plan::PencilPlanRFFT) where T = _alloc_array(T, plan.meta.spec_dims, plan.meta.comm)
end
if !isdefined(@__MODULE__, :alloc_arrays)
    alloc_arrays(plan::PencilPlanRFFT) = (alloc_phys(plan.meta.T_phys, plan),
                                          alloc_spec(plan.meta.T_spec, plan))
end

# 
# Safety checks
# 

function _check_compat(plan::PencilPlanRFFT, u_phys, u_spec)
    size(u_phys) == plan.meta.phys_dims ||
        throw(DimensionMismatch("Physical array dims mismatch: $(size(u_phys)) != $(plan.meta.phys_dims)"))
    eltype(u_phys) == plan.meta.T_phys ||
        throw(ArgumentError("Physical eltype mismatch: $(eltype(u_phys)) != $(plan.meta.T_phys)"))
    size(u_spec) == plan.meta.spec_dims ||
        throw(DimensionMismatch("Spectral array dims mismatch: $(size(u_spec)) != $(plan.meta.spec_dims)"))
    eltype(u_spec) == plan.meta.T_spec ||
        throw(ArgumentError("Spectral eltype mismatch: $(eltype(u_spec)) != $(plan.meta.T_spec)"))
end

# 
# Transform wrappers
# 

function forward_rfft!(plan::PencilPlanRFFT, u_phys, u_spec)
    _check_compat(plan, u_phys, u_spec)
    PencilFFTs.forward!(plan.forward, u_phys, u_spec)
    return u_spec
end

function backward_rfft!(plan::PencilPlanRFFT, u_spec, u_phys)
    _check_compat(plan, u_phys, u_spec)
    PencilFFTs.backward!(plan.backward, u_spec, u_phys)
    return u_phys
end

# 
# Local-indices helper (works for serial arrays too)
# 

if !isdefined(@__MODULE__, :localindices_dim)
    function localindices_dim(A, d::Int)
        if A isa PencilArrays.PencilArray
            return PencilArrays.localindices(A, d)
        else
            return axes(A, d)
        end
    end
end

if !isdefined(@__MODULE__, :localrange_dim)
    localrange_dim(A, d) = first(localindices_dim(A,d)):last(localindices_dim(A,d))
end

global_sizes(plan::PencilPlanRFFT) = plan.meta.dims

"""Convenience shim: return the input in serial; in MPI contexts provide a converter."""
pencilize_array(A::AbstractArray) = A

# 
# Pretty print
# 

function Base.show(io::IO, plan::PencilPlanRFFT)
    typ = plan.meta.real_transform ? "real<->complex" : "complex<->complex"
    print(io, "PencilPlanRFFT($typ, phys=$(plan.meta.phys_dims), spec=$(plan.meta.spec_dims))")
end

function plan_info(plan::PencilPlanRFFT)
    println("PencilPlanRFFT info:")
    println("  real_transform : ", plan.meta.real_transform)
    println("  phys_dims      : ", plan.meta.phys_dims)
    println("  spec_dims      : ", plan.meta.spec_dims)
    println("  eltypes        : ", plan.meta.T_phys, " -> ", plan.meta.T_spec)
    println("  comm size      : ", MPI.Comm_size(plan.meta.comm))
    println("  created        : ", Dates.unix2datetime(plan.meta.created_at))
end

# 
# Export
# 

# export make_pencil_plan_rfft, forward_rfft!, backward_rfft!,
#        alloc_arrays, alloc_phys, alloc_spec,
#        localindices_dim, localrange_dim, localview,
#        isparallel, isreal, get_comm,
#        eltype_physical, eltype_spectral,
#        physical_sizes, spectral_sizes

#end # module MPIPencilWrapper
